[package]
name = "keyfob"
version = "0.1.0"
edition = "2021"

[workspace]

[features]
default = []
aaronia_http = ["futuresdr/aaronia_http"]
soapy = ["futuresdr/soapy"]

[dependencies]
clap = { version = "4", features = ["derive"] }
futuresdr = { path = "../..", features=["seify"] }
